trigger:
  - development

pool:
  name: Default
  demands:
    - agent.name -equals iMac

jobs:
  - job: buildAndTest
    displayName: Build y pruebas con Docker
    steps:
      - checkout: self

      - script: |
          docker build -t phalcon-tdd:latest -f .devcontainer/Dockerfile .
        displayName: 'Construir imagen Docker'

      - script: |
          docker run --rm \
            -v $(Build.SourcesDirectory):/workspace \
            -w /workspace \
            phalcon-tdd sh -c "composer install && ./vendor/bin/phpunit StoreManager/Tests"
        displayName: 'Instalar dependencias y ejecutar pruebas'
